name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/298rehan/hvac-protection-platform-backend:latest

      - name: Build and push Customer Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./customer-frontend
          push: true
          tags: ghcr.io/298rehan/hvac-protection-platform-customer:latest

      - name: Build and push Admin Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./admin-frontend
          push: true
          tags: ghcr.io/298rehan/hvac-protection-platform-admin:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/hvac-project/hvac-protection-platform

            git pull origin main

            docker compose pull

            docker compose up -d

            docker image prune -f

            docker compose ps
